[build-system]
requires = ["setuptools>=61.0.0", "wheel", "setuptools-git-versioning<2"]
build-backend = "setuptools.build_meta"

[project]
name = "zigpy-znp"
dynamic = ["version"]
description = "A library for zigpy which communicates with TI ZNP radios"
urls = {repository = "https://github.com/zigpy/zigpy-znp"}
authors = [
    {name = "Alexei Chetroi", email = "alexei.chetroi@outlook.com"}
]
readme = "README.md"
license = {text = "GPL-3.0"}
requires-python = ">=3.11"
dependencies = [
    "zigpy>=1.5.0",
    "voluptuous",
    "coloredlogs",
    "jsonschema",
]

[tool.setuptools.packages.find]
exclude = ["tests", "tests.*"]

[dependency-groups]
testing = [
    "mypy==2.3.1",
    "pre-commit",
    "coverage[toml]",
    "pytest>=7.3.1",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    "pytest-mock>=3.10.0",
    "pytest-timeout>=2.1.0",
]
ci = [
    {include-group = "testing"},
    "pytest-github-actions-annotate-failures",
    "pytest-xdist",
]

[tool.setuptools-git-versioning]
enabled = true

[tool.pytest.ini_options]
addopts = "--showlocals --verbose"
testpaths = ["tests"]
timeout = 20
log_format = "%(asctime)s.%(msecs)03d %(levelname)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.ruff]
required-version = ">=0.5.0"
target-version = "py311"
line-length = 88

exclude = [
    ".venv",
    ".git",
    ".tox",
    "docs",
    "venv",
    "bin",
    "lib",
    "deps",
    "build",
]

[tool.ruff.lint]
select = [
    "B", # flake8-bugbear
    "C", # complexity
    "E", # pycodestyle
    "F", # pyflakes/autoflake
    "I", # isort
    "SIM", # flake8-simplify
    "UP", # pyupgrade
    "W", # pycodestyle
]

[tool.ruff.lint.mccabe]
max-complexity = 25

[tool.ruff.lint.isort]
force-sort-within-sections = true
known-first-party = [
    "zigpy_znp",
    "tests",
]
forced-separate = ["tests"]
combine-as-imports = true
split-on-trailing-comma = false

[tool.codespell]
skip = ["./.*", "tests/*", "pyproject.toml"]
quiet-level = 2

[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
show_error_codes = true
show_error_context = true
error_summary = true
exclude = ["^tests/"]
disable_error_code = [
    "attr-defined",
    "assignment",
    "arg-type",
    "union-attr",
    "var-annotated",
    "name-defined",
    "misc",
    "override",
    "return-value",
    "return",
    "type-arg",
    "list-item",
]

[tool.coverage.run]
source = ["zigpy_znp"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING:",
    "if typing.TYPE_CHECKING:",
    "raise NotImplementedError",
    "raise NotImplementedError()",
]
